### PR TITLE
XMPP

### PR DESCRIPTION
**Pull request by zootos**
Full support for XMPP

### CODE REVIEW

**Comment by zootos** [comment]
Tests run fine locally, both in IntelliJ and in using Maven. No idea why they crash in travis

**Comment by zootos** [comment]
The crashes might be due to an issue with the `eclipse-paho-mqtt-sn-gateway` library calling `System.exit(0)` which is not supported by TestNG

**Comment by zootos** [comment]
There we go

**Review by PhilipPuente — APPROVED** [review]
ok

**Pull request merged**
